[package]
name = "aoc_2020"
version = "0.1.0"
authors = ["Rudyard Richter <rudyardrichter@uchicago.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.20"
regex = "1"
